export const HTTP_REQUEST = 'HTTP_REQUEST';

export const SEARCH = 'SEARCH';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_RESET = 'SEARCH_RESET';


export const SEARCH_FIVE_DAILY = 'SEARCH_FIVE_DAILY';
export const SEARCH_FIVE_DAILY_REQUEST = 'SEARCH_FIVE_DAILY_REQUEST';
export const SEARCH_FIVE_DAILY_SUCCESS = 'SEARCH_FIVE_DAILY_SUCCESS';
export const SEARCH_FIVE_DAILY_FAILURE = 'SEARCH_FIVE_DAILY_FAILURE';